[pytest]
bdd_features_base_dir = tests/features
addopts =
    --tracing=retain-on-failure
    --screenshot=only-on-failure
    --video=retain-on-failure
    --output=reports/artifacts
    --html=reports/report.html --self-contained-html
    --junitxml=reports/junit.xml
